#!/bin/sh

clear

CUR_DIR=`pwd`

mvn package

rm -Rf $CUR_DIR/output

echo
echo ">>>>>> Launching jar"

hadoop jar target/word-count-1.0-SNAPSHOT.jar demo.word_count.WordCount $CUR_DIR/input $CUR_DIR/output

#export JAVA_HOME=`/usr/libexec/java_home`
#export HADOOP_CLASSPATH=${JAVA_HOME}/lib/tools.jar
#hadoop com.sun.tools.javac.Main ./src/main/java/demo/word_count/WordCount.java
#jar cf wc.jar -C ./src/main/java .
#hadoop jar wc.jar demo.word_count.WordCount ./input ./output
